package model;
// Generated 22-Oct-2014 00:04:03 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Songs generated by hbm2java
 */
public class Songs  implements java.io.Serializable {


     private Integer songId;
     private String name;
     private String artist;
     private String location;
     private String genere;
     private Date uploadedOn;
     private String path;

    public Songs() {
    }

    public Songs(String name, String artist, String location, String genere, Date uploadedOn, String path) {
       this.name = name;
       this.artist = artist;
       this.location = location;
       this.genere = genere;
       this.uploadedOn = uploadedOn;
       this.path = path;
    }
   
    public Integer getSongId() {
        return this.songId;
    }
    
    public void setSongId(Integer songId) {
        this.songId = songId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getArtist() {
        return this.artist;
    }
    
    public void setArtist(String artist) {
        this.artist = artist;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getGenere() {
        return this.genere;
    }
    
    public void setGenere(String genere) {
        this.genere = genere;
    }
    public Date getUploadedOn() {
        return this.uploadedOn;
    }
    
    public void setUploadedOn(Date uploadedOn) {
        this.uploadedOn = uploadedOn;
    }

    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }


}


